# Generated by Django 4.2.4 on 2023-08-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='vote1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='vote2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='vote3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='vote4',
            field=models.IntegerField(default=0),
        ),
    ]
