# Generated by Django 4.2.4 on 2023-08-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questions_is_closed_questions_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='vote',
            field=models.IntegerField(default=False, verbose_name='How many object created for this questions?'),
        ),
    ]
